[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && python app.py.py"
